version: '3.7'

services:
  k6:
    image: loadimpact/k6
    volumes:
      - .:/k6-tutorial
    working_dir: /k6-tutorial

  api:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/srv/k6-tutorial
      - /srv/k6-tutorial/node_modules
